/* import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import Sidebar from '../components/layouts/Sidebar'
import Header from '../components/layouts/Header'

export const metadata: Metadata = {
  title: process.env.APP_NAME,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="flex h-screen bg-gray-50">
      {/* 1. Sidebar - Fixed width on the left 
      <Sidebar />

      {/* 2. Main Content Area - Takes up the remaining width and is scrollable }
      <main className="flex-1 overflow-y-auto">
        <Header />
        {children}
      </main>
    </div>
  )
} 
*/

'use client'

import { useSidebar } from '@/context/SidebarContext'
import AppHeader from '@/layout/AppHeader'
import AppSidebar from '@/layout/AppSidebar'
// import AppHeader from '@/layout/AppHeader'
// import AppSidebar from '@/layout/AppSidebar'
// import Backdrop from '@/layout/Backdrop'
import React from 'react'

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  const { isExpanded, isHovered, isMobileOpen } = useSidebar()

  // Dynamic class for main content margin based on sidebar state
  const mainContentMargin = isMobileOpen
    ? 'ml-0'
    : isExpanded || isHovered
      ? 'lg:ml-[290px]'
      : 'lg:ml-[90px]'

  return (
    <div className="min-h-screen xl:flex">
      {/* Sidebar and Backdrop */}
      <AppSidebar />
      {/* <Backdrop /> */}
      {/* Main Content Area */}
      <div className={`flex-1 transition-all  duration-300 ease-in-out ${mainContentMargin}`}>
        {/* Header */}
        <AppHeader />
        {/* Page Content */}
        <div className="p-4 mx-auto max-w-(--breakpoint-2xl) md:p-6">{children}</div>
      </div>
    </div>
  )
}
